import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import axios from 'axios'
import { useState, useEffect } from 'react'
import {BsSearch} from 'react-icons/bs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [city, setCity] = useState('')
  const [weather, setWeather] = useState({})
  const [loadings, setLoadings] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=denver&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const fetchWeather =(e) => {
    e.preventDefault()
    setLoadings(true)
    axios.get(url).then((res) => {
      setWeather(res.data)
      console.log(res.data)
    })
    setCity('')
    setLoadings(false)
      
    }


  return (
    <>
      <Head>
        <title>Weather Next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

      
     
    </>
  )
}
